serverAddr = "__SERVER_IP__"
serverPort = 7000

[auth]
method = "token"
token = "__FRP_TOKEN__"

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000

[[proxies]]
name = "motor"
type = "tcp"
localIP = "127.0.0.1"
localPort = 9876
remotePort = 6001
